export type MockCity = {
  id: string;
  slug: string;
  name: string;
  region: string;
};

export type MockDistributor = {
  id: string;
  slug: string;
  name: string;
  citySlug: string;
  address: string;
  latitude: number;
  longitude: number;
  departmentCode: string;
  departmentName: string;
  totalBoxes: number;
};

/** Villes mock — réseau KeyNest France. */
export const MOCK_CITIES: MockCity[] = [
  { id: "city_paris", slug: "paris", name: "Paris", region: "Île-de-France" },
  { id: "city_lyon", slug: "lyon", name: "Lyon", region: "Auvergne-Rhône-Alpes" },
  { id: "city_marseille", slug: "marseille", name: "Marseille", region: "Provence-Alpes-Côte d'Azur" },
  { id: "city_nice", slug: "nice", name: "Nice", region: "Provence-Alpes-Côte d'Azur" },
  { id: "city_bordeaux", slug: "bordeaux", name: "Bordeaux", region: "Nouvelle-Aquitaine" },
  { id: "city_toulouse", slug: "toulouse", name: "Toulouse", region: "Occitanie" },
  { id: "city_nantes", slug: "nantes", name: "Nantes", region: "Pays de la Loire" },
  { id: "city_lille", slug: "lille", name: "Lille", region: "Hauts-de-France" },
  { id: "city_strasbourg", slug: "strasbourg", name: "Strasbourg", region: "Grand Est" },
  { id: "city_rennes", slug: "rennes", name: "Rennes", region: "Bretagne" },
  { id: "city_montpellier", slug: "montpellier", name: "Montpellier", region: "Occitanie" },
  { id: "city_grenoble", slug: "grenoble", name: "Grenoble", region: "Auvergne-Rhône-Alpes" },
  { id: "city_nancy", slug: "nancy", name: "Nancy", region: "Grand Est" },
  { id: "city_reims", slug: "reims", name: "Reims", region: "Grand Est" },
];

/** Distributeurs avec adresses réelles et coordonnées GPS. */
export const MOCK_DISTRIBUTORS: MockDistributor[] = [
  {
    id: "dist_paris_opera",
    slug: "paris-opera",
    name: "Opéra",
    citySlug: "paris",
    address: "1 Place de l'Opéra, 75009 Paris",
    latitude: 48.871969,
    longitude: 2.331601,
    departmentCode: "75",
    departmentName: "Paris",
    totalBoxes: 12,
  },
  {
    id: "dist_paris_montmartre",
    slug: "paris-montmartre",
    name: "Montmartre",
    citySlug: "paris",
    address: "35 Rue du Chevalier de la Barre, 75018 Paris",
    latitude: 48.886705,
    longitude: 2.343104,
    departmentCode: "75",
    departmentName: "Paris",
    totalBoxes: 8,
  },
  {
    id: "dist_paris_gare_nord",
    slug: "paris-gare-nord",
    name: "Gare du Nord",
    citySlug: "paris",
    address: "112 Rue de Maubeuge, 75010 Paris",
    latitude: 48.880184,
    longitude: 2.354151,
    departmentCode: "75",
    departmentName: "Paris",
    totalBoxes: 10,
  },
  {
    id: "dist_lyon_partdieu",
    slug: "lyon-part-dieu",
    name: "Part-Dieu",
    citySlug: "lyon",
    address: "5 Place Charles-Béraudier, 69003 Lyon",
    latitude: 45.760559,
    longitude: 4.860415,
    departmentCode: "69",
    departmentName: "Rhône",
    totalBoxes: 10,
  },
  {
    id: "dist_lyon_bellecour",
    slug: "lyon-bellecour",
    name: "Bellecour",
    citySlug: "lyon",
    address: "2 Place Bellecour, 69002 Lyon",
    latitude: 45.757814,
    longitude: 4.832011,
    departmentCode: "69",
    departmentName: "Rhône",
    totalBoxes: 6,
  },
  {
    id: "dist_marseille_vieuxport",
    slug: "marseille-vieux-port",
    name: "Vieux-Port",
    citySlug: "marseille",
    address: "1 Quai des Belges, 13001 Marseille",
    latitude: 43.295128,
    longitude: 5.374567,
    departmentCode: "13",
    departmentName: "Bouches-du-Rhône",
    totalBoxes: 8,
  },
  {
    id: "dist_marseille_joliette",
    slug: "marseille-joliette",
    name: "Joliette",
    citySlug: "marseille",
    address: "15 Avenue Robert Schuman, 13002 Marseille",
    latitude: 43.306978,
    longitude: 5.366314,
    departmentCode: "13",
    departmentName: "Bouches-du-Rhône",
    totalBoxes: 6,
  },
  {
    id: "dist_nice_promenade",
    slug: "nice-promenade",
    name: "Promenade des Anglais",
    citySlug: "nice",
    address: "15 Promenade des Anglais, 06000 Nice",
    latitude: 43.694742,
    longitude: 7.265342,
    departmentCode: "06",
    departmentName: "Alpes-Maritimes",
    totalBoxes: 6,
  },
  {
    id: "dist_nice_gare",
    slug: "nice-gare",
    name: "Gare Nice-Ville",
    citySlug: "nice",
    address: "12 Avenue Thiers, 06000 Nice",
    latitude: 43.704556,
    longitude: 7.261904,
    departmentCode: "06",
    departmentName: "Alpes-Maritimes",
    totalBoxes: 4,
  },
  {
    id: "dist_bordeaux_bourse",
    slug: "bordeaux-bourse",
    name: "Place de la Bourse",
    citySlug: "bordeaux",
    address: "1 Place de la Bourse, 33000 Bordeaux",
    latitude: 44.841789,
    longitude: -0.5715,
    departmentCode: "33",
    departmentName: "Gironde",
    totalBoxes: 10,
  },
  {
    id: "dist_bordeaux_gare",
    slug: "bordeaux-gare",
    name: "Gare Saint-Jean",
    citySlug: "bordeaux",
    address: "30 Rue Charles Domercq, 33800 Bordeaux",
    latitude: 44.825874,
    longitude: -0.556693,
    departmentCode: "33",
    departmentName: "Gironde",
    totalBoxes: 8,
  },
  {
    id: "dist_toulouse_capitole",
    slug: "toulouse-capitole",
    name: "Capitole",
    citySlug: "toulouse",
    address: "1 Place du Capitole, 31000 Toulouse",
    latitude: 43.604462,
    longitude: 1.444247,
    departmentCode: "31",
    departmentName: "Haute-Garonne",
    totalBoxes: 8,
  },
  {
    id: "dist_toulouse_compans",
    slug: "toulouse-compans",
    name: "Compans-Caffarelli",
    citySlug: "toulouse",
    address: "9 Esplanade Compans Caffarelli, 31000 Toulouse",
    latitude: 43.611242,
    longitude: 1.433892,
    departmentCode: "31",
    departmentName: "Haute-Garonne",
    totalBoxes: 6,
  },
  {
    id: "dist_nantes_gare",
    slug: "nantes-gare",
    name: "Gare Sud",
    citySlug: "nantes",
    address: "27 Boulevard de Stalingrad, 44000 Nantes",
    latitude: 47.217542,
    longitude: -1.542077,
    departmentCode: "44",
    departmentName: "Loire-Atlantique",
    totalBoxes: 8,
  },
  {
    id: "dist_nantes_chateau",
    slug: "nantes-chateau",
    name: "Château des Ducs",
    citySlug: "nantes",
    address: "4 Place Marc Elder, 44000 Nantes",
    latitude: 47.216299,
    longitude: -1.550328,
    departmentCode: "44",
    departmentName: "Loire-Atlantique",
    totalBoxes: 4,
  },
  {
    id: "dist_lille_flandres",
    slug: "lille-flandres",
    name: "Gare Flandres",
    citySlug: "lille",
    address: "50 Place de la Gare, 59800 Lille",
    latitude: 50.636563,
    longitude: 3.070472,
    departmentCode: "59",
    departmentName: "Nord",
    totalBoxes: 8,
  },
  {
    id: "dist_lille_euralille",
    slug: "lille-euralille",
    name: "Euralille",
    citySlug: "lille",
    address: "100 Avenue Willy Brandt, 59777 Lille",
    latitude: 50.636331,
    longitude: 3.075829,
    departmentCode: "59",
    departmentName: "Nord",
    totalBoxes: 6,
  },
  {
    id: "dist_strasbourg_petitefrance",
    slug: "strasbourg-petite-france",
    name: "Petite France",
    citySlug: "strasbourg",
    address: "3 Petite Rue des Dentelles, 67000 Strasbourg",
    latitude: 48.581042,
    longitude: 7.742611,
    departmentCode: "67",
    departmentName: "Bas-Rhin",
    totalBoxes: 6,
  },
  {
    id: "dist_strasbourg_gare",
    slug: "strasbourg-gare",
    name: "Gare Centrale",
    citySlug: "strasbourg",
    address: "20 Place de la Gare, 67000 Strasbourg",
    latitude: 48.585042,
    longitude: 7.734453,
    departmentCode: "67",
    departmentName: "Bas-Rhin",
    totalBoxes: 4,
  },
  {
    id: "dist_rennes_gare",
    slug: "rennes-gare",
    name: "Gare Rennes",
    citySlug: "rennes",
    address: "19 Rue du Champ de Mars, 35000 Rennes",
    latitude: 48.103762,
    longitude: -1.672744,
    departmentCode: "35",
    departmentName: "Ille-et-Vilaine",
    totalBoxes: 6,
  },
  {
    id: "dist_montpellier_comedie",
    slug: "montpellier-comedie",
    name: "Comédie",
    citySlug: "montpellier",
    address: "1 Place de la Comédie, 34000 Montpellier",
    latitude: 43.608625,
    longitude: 3.879831,
    departmentCode: "34",
    departmentName: "Hérault",
    totalBoxes: 6,
  },
  {
    id: "dist_montpellier_gare",
    slug: "montpellier-gare",
    name: "Gare Saint-Roch",
    citySlug: "montpellier",
    address: "1 Place Auguste Gibert, 34000 Montpellier",
    latitude: 43.604739,
    longitude: 3.880674,
    departmentCode: "34",
    departmentName: "Hérault",
    totalBoxes: 4,
  },
  {
    id: "dist_grenoble_gare",
    slug: "grenoble-gare",
    name: "Gare Grenoble",
    citySlug: "grenoble",
    address: "16 Place de la Gare, 38000 Grenoble",
    latitude: 45.191601,
    longitude: 5.714411,
    departmentCode: "38",
    departmentName: "Isère",
    totalBoxes: 6,
  },
  {
    id: "dist_nancy_stanislas",
    slug: "nancy-stanislas",
    name: "Place Stanislas",
    citySlug: "nancy",
    address: "2 Place Stanislas, 54000 Nancy",
    latitude: 48.693524,
    longitude: 6.18327,
    departmentCode: "54",
    departmentName: "Meurthe-et-Moselle",
    totalBoxes: 4,
  },
  {
    id: "dist_reims_cathedrale",
    slug: "reims-cathedrale",
    name: "Cathédrale",
    citySlug: "reims",
    address: "2 Rue Guillaume de Machault, 51100 Reims",
    latitude: 49.253768,
    longitude: 4.03409,
    departmentCode: "51",
    departmentName: "Marne",
    totalBoxes: 4,
  },
];
